export const API_ENDPOINTS = {
  AUTH: {
    REGISTER: '/auth/register',
    LOGIN: '/auth/login',
    REFRESH: '/auth/refresh',
    LOGOUT: '/auth/logout',
    ME: '/auth/me',
  },
  USERS: {
    ME: '/users/me',
    SAVED_DUAS: '/users/me/saved-duas',
    PROFILE: (username: string) => `/users/${username}`,
  },
  DUAS: {
    LIST: '/duas',
    DETAIL: (id: string) => `/duas/${id}`,
    CREATE: '/duas',
    UPDATE: (id: string) => `/duas/${id}`,
    DELETE: (id: string) => `/duas/${id}`,
    SAVE: (id: string) => `/duas/${id}/save`,
    UNSAVE: (id: string) => `/duas/${id}/save`,
    REFERENCES: (id: string) => `/duas/${id}/references`,
    AUDIOS: (id: string) => `/duas/${id}/audios`,
  },
  CATEGORIES: {
    LIST: '/categories',
    DETAIL: (slug: string) => `/categories/${slug}`,
    CREATE: '/categories',
    UPDATE: (id: string) => `/categories/${id}`,
    DELETE: (id: string) => `/categories/${id}`,
  },
  SOURCES: {
    LIST: '/sources',
    DETAIL: (id: string) => `/sources/${id}`,
    CREATE: '/sources',
    UPDATE: (id: string) => `/sources/${id}`,
    DELETE: (id: string) => `/sources/${id}`,
  },
  FEED: {
    GET: '/feed',
  },
  POSTS: {
    CREATE: '/posts',
    DETAIL: (id: string) => `/posts/${id}`,
    UPDATE: (id: string) => `/posts/${id}`,
    DELETE: (id: string) => `/posts/${id}`,
    SAVE: (id: string) => `/posts/${id}/save`,
    UNSAVE: (id: string) => `/posts/${id}/save`,
    REACTION: (id: string) => `/posts/${id}/reaction`,
    UNREACTION: (id: string) => `/posts/${id}/reaction`,
    COMMENTS: (id: string) => `/posts/${id}/comments`,
    CREATE_COMMENT: (id: string) => `/posts/${id}/comments`,
  },
  FRIENDS: {
    LIST: '/friends',
    RECEIVED_REQUESTS: '/friends/requests/received',
    SENT_REQUESTS: '/friends/requests/sent',
    STATUS: (userId: string) => `/friends/status/${userId}`,
    SEND_REQUEST: '/friends/requests',
    CANCEL_REQUEST: (requestId: string) => `/friends/requests/${requestId}`,
    ACCEPT_REQUEST: (requestId: string) => `/friends/requests/${requestId}/accept`,
    REJECT_REQUEST: (requestId: string) => `/friends/requests/${requestId}/reject`,
    UNFRIEND: (userId: string) => `/friends/${userId}`,
  },
} as const;
