export const ROUTES = {
  HOME: '/',
  DUAS: '/duas',
  DUA_DETAIL: (id: string) => `/duas/${id}`,
  CATEGORIES: '/categories',
  CATEGORY_DETAIL: (slug: string) => `/categories/${slug}`,
  SEARCH: '/search',
  LOGIN: '/login',
  REGISTER: '/register',
  SAVED: '/saved',
  PROFILE: '/profile',
  SETTINGS: '/settings',
  USER_PROFILE: (username: string) => `/${username}`,
  FRIENDS: {
    HOME: '/friends',
    REQUESTS: '/friends/requests',
    LIST: '/friends/list',
    SENT: '/friends/sent',
  },
  GROUPS: {
    HOME: '/groups',
    CREATE: '/groups/create',
    DETAIL: (slug: string) => `/groups/${slug}`,
    MEMBERS: (slug: string) => `/groups/${slug}/members`,
    REQUESTS: (slug: string) => `/groups/${slug}/requests`,
    SETTINGS: (slug: string) => `/groups/${slug}/settings`,
  },
  BLOOD: {
    HOME: '/blood',
    CREATE: '/blood/create',
    DONORS: '/blood/donors',
    DETAIL: (id: string) => `/blood/${id}`,
  },
  ADMIN: {
    HOME: '/admin',
    DUAS: '/admin/duas',
    CATEGORIES: '/admin/categories',
    SOURCES: '/admin/sources',
  },
} as const;
